[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/.well-known/farcaster.json"
  to = "/api/manifest"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 